variables:
  APP_NAME: ${CI_PROJECT_NAME}
  REPO_NAME: "fichap-team/microservices"
  REPO_DOCKER: ${CI_REGISTRY}/${REPO_NAME}
  DOCKERFILE: .
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  INGRESS_PATH: ""

before_script:
  - export BUILD_VERSION=$(cat package.json | grep \"version\" | cut -d "\"" -f4)

stages:
  - CodeQuality
  - Package
  - Deploy
  - Promotion
  - IncreaseVersion

include:
  - project: "fichap-team/microservices/fichap-ci"
    ref: "master"
    file:
      - "Package.yml"
      - "CodeQuality.yml"
      - "DeployWeb.yml"
      - "IncreaseVersion.yml"
