const translates = {
  "Aún no hay tipos de eventos": "Not any type of events yet",
  "Aún no hay eventos": "No events yet",
  EarlyArrival: "Early arrival",
  NewManualWorkday: "New manual workday",
  Create: "Create",
  Heatmap: "Heatmap",
  Próximos: "Next",
  Pasados: "Previous",
  "Compartir enlaces del tipo de evento con los eventos programados":
    "Share event type links with scheduled events",
  FaceToFace: "Face to face",
  day1: "M",
  day2: "T",
  day3: "W",
  day4: "T",
  day5: "F",
  day6: "S",
  day0: "S",
  _day1: "Mon",
  _day2: "Tue",
  _day3: "Wed",
  _day4: "Thu",
  _day5: "Fri",
  _day6: "Sat",
  _day0: "Sun",
  Jan: "Jan",
  TextHere: "Complete",
  DurationInMinutes: "Duration in minutes",
  "Calendario de Google": "Google calendar",
  Feb: "Feb",
  weekday1: "M",
  weekday2: "T",
  weekday3: "W",
  weekday4: "T",
  weekday5: "F",
  weekday6: "S",
  weekday0: "S",
  weekday3letters0: "Sun",
  weekday3letters1: "Mon",
  weekday3letters2: "Tue",
  weekday3letters3: "Wed",
  weekday3letters4: "Thu",
  weekday3letters5: "Fri",
  weekday3letters6: "Sat",
  notImageError: "image is required",
};

export default translates;
