const translates = {
  Events: "Eventos",
  "Type of events": "Tipo de eventos",
  Availability: "Disponibilidad",
  "Calendar conection": "Conexión del calendario",
  "Configurate availability": "Configurar disponibilidad",
  "Configurate your weekly available hours":
    "Configurar sus horarios semanales",
  "Times overlap with another set of times":
    "Los horarios no pueden pisarse entre sí",
  ReviewMark: "Revisión",
  Edit: "Editar",
  Clone: "Clonar",
  Connect: "Conectar",
  FaceToFace: "Cara a cara",
  Another: "Otro",
  "Location/Medium": "Ubicación/Medio",
  "Location": "Ubicación",
  Wednesday: "miércoles",
  Monday: "lunes",
  Thursday: "martes",
  Tuesday: "jueves",
  Friday: "viernes",
  Saturday: "sabado",
  Sunday: "domingo",
  Connected: "Conectado",
  TextHere: "Completar",
  Inviteds: "Invitados",
  AreYouSure: "¿Estás seguro?",
  Cancel: "Cancelar",
  Delete: "Eliminar",
  "Start hour": "Hora de inicio",
  Date: "Fecha",
  "Finish hour": "Hora de fin",
  Invited: "Invitado",
  "Type of event": "Tipo de evento",
  Save: "Guardar",
  Actions: "Acciones",
  Create: "Crear",
  "Name of the event": "Nombre del evento",
  DurationInMinutes: "Duracion en minutos",
  "Create event": "Crear evento",
  notImageError: "La imagen es requerida",
  "Selected image can't be heavier than 1mb":
    "La imagen seleccionada no puede pesar más de 1mb",
  _day1: "Lun",
  _day2: "Mar",
  _day3: "Mie",
  _day4: "Jue",
  _day5: "Vie",
  _day6: "Sab",
  _day0: "Dom",
  Jan: "Ene",
  Feb: "Feb",
  weekday1: "L",
  weekday2: "M",
  weekday3: "M",
  weekday4: "J",
  weekday5: "V",
  weekday6: "S",
  weekday0: "D",
  weekday3letters0: "Dom",
  weekday3letters1: "Lun",
  weekday3letters2: "Mar",
  weekday3letters3: "Mie",
  weekday3letters4: "Jue",
  weekday3letters5: "Vie",
  weekday3letters6: "Sab",
};

export default translates;
