export const timezoneData = [
  { gtm: '', value: -720, label: 'International Date Line West (GMT-12:00)' },
  { gtm: '', value:-660, label: 'Midway Island, Samoa (GMT-11:00)' },
  { gtm: '', value: -600, label: 'Hawaii (GMT-10:00)' },
  { gtm: '', value: -540, label: 'Alaska (GMT-09:00)' },
  {
    gtm: '',
    value: -480,
    label: 'Pacific Time (US and Canada); Tijuana (GMT-08:00)',
  },
  { gtm: '', value: -420, label: 'Mountain Time (US and Canada) (GMT-07:00)' },
  { gtm: '', value: -420, label: 'Chihuahua, La Paz, Mazatlan (GMT-07:00)' },
  { gtm: '', value: -360, label: 'Central Time (US and Canada (GMT-06:00)' },
  { gtm: '', value: -360, label: 'Guadalajara, Mexico City, Monterrey (GMT-06:00)' },
  { gtm: '', value: -300, label: 'Bogota, Lima, Quito (GMT-05:00)' },
  { gtm: '', value: -300, label: 'Eastern Time (US and Canada) (GMT-05:00)' },
  { gtm: '(GMT-04:00)', value: -240, label: 'Atlantic Time (Canada)' },
  { gtm: '(GMT-04:00)', value: -240, label: 'Caracas, La Paz' },
  { gtm: '(GMT-04:00)', value: -240, label: 'Santiago' },
  { gtm: '(GMT-03:00)', value: -180, label: 'Buenos Aires Argentina, Brasilia' },
  { gtm: '(GMT-02:00)', value: 0, label: 'Mid-Atlantic' },
  { gtm: '(GMT-01:00)', value: 0, label: 'Azores' },
  { gtm: '(GMT-01:00)', value: 0, label: 'Cape Verde Islands' },
  { gtm: '(GMT)', value: 0, label: 'Dublin Edinburgh, Lisbon, London' },
  { gtm: '(GMT+01:00)', value: 60, label: 'Copenhagen, Madrid, Paris' },
  {
    gtm: '(GMT+02:00)',
    value: 120,
    label: 'Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius',
  },
  { gtm: '(GMT+02:00)', value: 120, label: 'Athens, Istanbul, Minsk' },
  { gtm: '(GMT+02:00)', value: 120, label: 'Jerusalem' },
  { gtm: '(GMT+02:00)', value: 120, label: 'Harare, Pretoria' },
  { gtm: '(GMT+03:00)', value: 180, label: 'Moscow, St. Petersburg, Volgograd' },
  { gtm: '(GMT+03:00)', value: 180, label: 'Kuwait, Riyadh' },
  { gtm: '(GMT+03:00)', value: 180, label: 'Nairobi' },
  { gtm: '(GMT+03:00)', value: 180, label: 'Baghdad' },
  { gtm: '(GMT+04:00)', value: 240, label: 'Abu Dhabi, Muscat' },
  { gtm: '(GMT+04:00)', value: 240, label: 'Baku, Tbilisi, Yerevan' },
  { gtm: '(GMT+05:00)', value: 300, label: 'Ekaterinburg' },
  { gtm: '(GMT+05:00)', value: 300, label: 'Islamabad, Karachi, Tashkent' },
  { gtm: '(GMT+06:00)', value: 360, label: 'Astana, Dhaka' },
  { gtm: '(GMT+07:00)', value: 420, label: 'Bangkok, Hanoi, Jakarta' },
  {
    gtm: '(GMT+08:00)',
    value: 480,
    label: 'Beijing, Chongqing, Hong Kong, Singapore',
  },
  { gtm: '(GMT+09:00)', value: 540, label: 'Tokyo, Yakutsk' },
  { gtm: '(GMT+10:00)', value: 600, label: 'Canberra, Melbourne, Sydney' },
  {
    gtm: '(GMT+11:00)',
    value: 660,
    label: 'Magadan, Solomon Islands, New Caledonia',
  },
  {
    gtm: '(GMT+12:00)',
    value: 720,
    label: 'Fiji Islands, Kamchatka, Marshall Islands, Wellington',
  },
  { gtm: '(GMT+13:00)', value: 780, label: "Nuku'alofa" },
];
